apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: boink-stopper
  namespace: test
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:      
      template:
        spec:
          serviceAccountName: boink
          containers:
          - name: boink
            image: boink:1.0
            command: ["/boink"]
            args: ["--namespace","test", "--label", "app=nginx", "--action" , "stop"]
          restartPolicy: OnFailure