---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: boink
  namespace: test

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: boink
rules:
- apiGroups: ["extensions","apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: boink
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: boink
subjects:
- kind: ServiceAccount
  name: boink
  namespace: test

